<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="pytest" skips="0" tests="6" time="284.429"><testcase classname="testreadandanalyse" file="testreadandanalyse.py" line="13" name="test_init_correct" time="1.87134504318"></testcase><testcase classname="testreadandanalyse" file="testreadandanalyse.py" line="18" name="test_init_ErrorMongo" time="1.64866995811"><system-err>mongodbaccess.py            42 ERROR    Authentication failure
</system-err></testcase><testcase classname="testreadandanalyse" file="testreadandanalyse.py" line="23" name="test_init_ErrorMail" time="3.24396514893"><system-err>mailaccess.py               36 ERROR    error loggin eMail
</system-err></testcase><testcase classname="testreadandanalyse" file="testreadandanalyse.py" line="28" name="test_findingMails" time="11.8687272072"></testcase><testcase classname="testreadandanalyse" file="testreadandanalyse.py" line="36" name="test_findingUrls" time="110.905798674"></testcase><testcase classname="testreadandanalyse" file="testreadandanalyse.py" line="60" name="test_scrapUrls" time="154.478762865"></testcase></testsuite>